# Generated by Django 5.1.1 on 2024-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('isbn', models.IntegerField()),
                ('backCover', models.CharField(max_length=300)),
                ('cover', models.BooleanField()),
            ],
        ),
    ]
